# Clock signal
set_property PACKAGE_PIN W5 [get_ports clk_i_100]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk_i_100]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk_i_100]
	
# LEDs out
set_property PACKAGE_PIN U16 [get_ports {data_o_uart[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {data_o_uart[0]}]
set_property PACKAGE_PIN E19 [get_ports {data_o_uart[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {data_o_uart[1]}]
set_property PACKAGE_PIN U19 [get_ports {data_o_uart[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {data_o_uart[2]}]
set_property PACKAGE_PIN V19 [get_ports {data_o_uart[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {data_o_uart[3]}]
set_property PACKAGE_PIN W18 [get_ports {data_o_uart[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {data_o_uart[4]}]
set_property PACKAGE_PIN U15 [get_ports {data_o_uart[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {data_o_uart[5]}]
set_property PACKAGE_PIN U14 [get_ports {data_o_uart[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {data_o_uart[6]}]
set_property PACKAGE_PIN V14 [get_ports {data_o_uart[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {data_o_uart[7]}]
	
	
# USB-RS232 Interface
set_property PACKAGE_PIN B18 [get_ports rx]						
	set_property IOSTANDARD LVCMOS33 [get_ports rx]
	
# reset button (up)
set_property PACKAGE_PIN T18 [get_ports reset]						
    set_property IOSTANDARD LVCMOS33 [get_ports reset]
# right button
set_property PACKAGE_PIN T17 [get_ports mode_change]						
	set_property IOSTANDARD LVCMOS33 [get_ports mode_change]
    
# VGA Connector
set_property PACKAGE_PIN G19 [get_ports {vga_r[0]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[0]}]
set_property PACKAGE_PIN H19 [get_ports {vga_r[1]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[1]}]
set_property PACKAGE_PIN J19 [get_ports {vga_r[2]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[2]}]
set_property PACKAGE_PIN N19 [get_ports {vga_r[3]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[3]}]
set_property PACKAGE_PIN N18 [get_ports {vga_b[0]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[0]}]
set_property PACKAGE_PIN L18 [get_ports {vga_b[1]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[1]}]
set_property PACKAGE_PIN K18 [get_ports {vga_b[2]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[2]}]
set_property PACKAGE_PIN J18 [get_ports {vga_b[3]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[3]}]
set_property PACKAGE_PIN J17 [get_ports {vga_g[0]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[0]}]
set_property PACKAGE_PIN H17 [get_ports {vga_g[1]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[1]}]
set_property PACKAGE_PIN G17 [get_ports {vga_g[2]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[2]}]
set_property PACKAGE_PIN D17 [get_ports {vga_g[3]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[3]}]
set_property PACKAGE_PIN P19 [get_ports h_sync]						
	set_property IOSTANDARD LVCMOS33 [get_ports h_sync]
set_property PACKAGE_PIN R19 [get_ports v_sync]						
	set_property IOSTANDARD LVCMOS33 [get_ports v_sync]